# Generated by Django 5.2.1 on 2025-07-08 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('site_rattachement', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('commercial', 'Commercial'), ('responsable', 'Responsable'), ('admin', 'Admin')], default='commercial', max_length=20)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FrontClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('civilite', models.CharField(blank=True, max_length=50, null=True)),
                ('rs_nom', models.CharField(blank=True, max_length=64, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('en_compte', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=False)),
                ('code_comptable', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('email_comptabilite', models.CharField(blank=True, max_length=254, null=True)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commercial_id', models.BigIntegerField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'front_client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImportClientCorrected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, max_length=50, null=True)),
                ('rs_nom', models.CharField(blank=True, max_length=64, null=True)),
                ('prénom', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=60, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=60, null=True)),
                ('commercial', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=60, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('code_comptable', models.CharField(blank=True, max_length=64, null=True)),
                ('e_mail_comptabilité', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'import_clients_corrected',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('RDV_AJOUTE', 'RDV Ajouté'), ('RDV_VALIDE', 'RDV Validé'), ('RDV_ANNULE', 'RDV Annulé'), ('CLIENT_AJOUTE', 'Client Ajouté')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ville', models.CharField(blank=True, max_length=60, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='front.frontclient')),
            ],
            options={
                'db_table': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('objet', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_statut', models.DateTimeField(blank=True, null=True)),
                ('statut_rdv', models.CharField(choices=[('a_venir', 'À venir'), ('valide', 'Validé'), ('annule', 'Annulé')], default='a_venir', max_length=16)),
                ('rs_nom', models.CharField(blank=True, max_length=128, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.importclientcorrected')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommentaireRdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rs_nom', models.CharField(blank=True, max_length=128, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial')),
                ('rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='front.rendezvous')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SatisfactionB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base64', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('rs_nom', models.CharField(default='Inconnu', max_length=255)),
                ('satisfaction_qualite_pieces', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('note_qualite_pieces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('probleme_qualite_piece', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('type_probleme_qualite_piece', models.TextField(blank=True, null=True)),
                ('satisfaction_delai_livraison', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('delai_livraison_moyen', models.CharField(blank=True, max_length=20, null=True)),
                ('delai_livraison_ideal', models.CharField(blank=True, max_length=20, null=True)),
                ('delai_livraison_ideal_autre', models.TextField(blank=True, null=True)),
                ('recours_sav', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('note_sav', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('piece_non_dispo', models.TextField(blank=True, null=True)),
                ('satisfaction_experience_rubio', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('personnel_joignable', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('note_accueil', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commande_simple', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True)),
                ('moyen_commande', models.CharField(blank=True, max_length=20, null=True)),
                ('moyen_commande_autre', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('motivation_commande', models.TextField(blank=True, null=True)),
                ('note_recommandation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial')),
                ('rdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.rendezvous')),
            ],
        ),
    ]
