# Generated by Django 5.2.1 on 2025-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='date_statut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
