# Generated by Django 5.2.1 on 2025-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontclient',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
