# Generated by Django 5.2.1 on 2025-05-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='mot_de_passe',
            new_name='password',
        ),
    ]
