# Generated by Django 5.2.1 on 2025-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_rendezvous_date_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairerdv',
            name='rs_nom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
