# Generated by Django 5.2.1 on 2025-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_frontclient_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontclient',
            name='commercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
