# Generated by Django 5.2.1 on 2025-05-20 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_rename_mot_de_passe_commercial_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.commercial'),
        ),
        migrations.CreateModel(
            name='CommentaireRdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='front.rendezvous')),
            ],
        ),
    ]
