# Generated by Django 5.2.1 on 2025-07-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_frontclient_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importclientcorrected',
            name='en_compte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.frontclient'),
        ),
    ]
