# Generated by Django 5.2.1 on 2025-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_commentairerdv_rs_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statut_rdv',
            field=models.CharField(choices=[('a_venir', 'À venir'), ('valide', 'Validé'), ('annule', 'Annulé')], default='a_venir', max_length=16),
        ),
    ]
