# Generated by Django 5.2.1 on 2025-06-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_rendezvous_statut_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairerdv',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial'),
        ),
    ]
