# Generated by Django 5.2.1 on 2025-07-09 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_importclientcorrected_en_compte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionb2b',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
