# Generated by Django 5.2.1 on 2025-07-09 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_satisfactionb2b_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionb2b',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
