# Generated by Django 5.2 on 2025-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_commentairerdv_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite_satisfait', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('note_qualite_globale', models.PositiveSmallIntegerField()),
                ('probleme_qualite', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('type_probleme', models.TextField(blank=True, null=True)),
                ('delai_satisfait', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('delai_moyen', models.CharField(choices=[('moins_24h', 'Moins de 24h'), ('1_2j', '1-2 jours'), ('3_4j', '3-4 jours'), ('plus_5j', 'Plus de 5 jours')], max_length=12)),
                ('delai_ideal', models.CharField(choices=[('moins_24h', 'Moins de 24h'), ('1_2j', '1-2 jours'), ('3_4j', '3-4 jours'), ('autre', 'Autre')], max_length=12)),
                ('delai_ideal_autre', models.CharField(blank=True, max_length=64, null=True)),
                ('recours_sav', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('note_sav', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pieces_non_dispo', models.TextField(blank=True, null=True)),
                ('experience_satisfait', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('personnel_joignable', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('note_accueil', models.PositiveSmallIntegerField()),
                ('commande_simple', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('moyen_commande', models.CharField(choices=[('telephone', 'Téléphone'), ('mail', 'Mail'), ('site_web', 'Site web'), ('terrain', 'Commercial terrain'), ('autre', 'Autre')], max_length=16)),
                ('moyen_commande_autre', models.CharField(blank=True, max_length=64, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('motivation_commande', models.TextField(blank=True, null=True)),
                ('note_recommandation', models.PositiveSmallIntegerField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
