# Generated by Django 5.2.1 on 2025-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_satisfactionb2b_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionb2b',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
