# Generated by Django 5.2.1 on 2025-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_satisfactionb2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionb2b',
            name='pdf_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
