# Generated by Django 5.2.1 on 2025-06-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_satisfactionb2b_pdf_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='commande_simple',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='delai_ideal',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='delai_ideal_autre',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='delai_moyen',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='delai_satisfait',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='experience_satisfait',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='motivation_commande',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='moyen_commande',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='moyen_commande_autre',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='note_accueil',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='note_qualite_globale',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='note_recommandation',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='note_sav',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='personnel_joignable',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='pieces_non_dispo',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='probleme_qualite',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='qualite_satisfait',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='recours_sav',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='satisfactionb2b',
            name='type_probleme',
        ),
    ]
