# Generated by Django 5.2.1 on 2025-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_satisfactionb2b_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionb2b',
            name='score_hybride',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
