# Generated by Django 5.2.1 on 2025-06-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_remove_satisfactionb2b_commande_simple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionb2b',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial'),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='rdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.rendezvous'),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='rs_nom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
    ]
