# Generated by Django 5.2.1 on 2025-06-12 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_satisfactionb2b_commercial_satisfactionb2b_rdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
