# Generated by Django 5.2.1 on 2025-07-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_adresse_geocode_date_adresse_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut_rdv',
            field=models.CharField(choices=[('a_venir', 'À venir'), ('valide', 'Validé'), ('annule', 'Annulé'), ('gele', 'Gelé')], default='a_venir', max_length=16),
        ),
    ]
