# Generated by Django 5.2.1 on 2025-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_rendezvous_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionb2b',
            name='commande_simple',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='delai_livraison_ideal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='delai_livraison_ideal_autre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='delai_livraison_moyen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='motivation_commande',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='moyen_commande',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='moyen_commande_autre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='note_accueil',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='note_qualite_pieces',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='note_recommandation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='note_sav',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='personnel_joignable',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='piece_non_dispo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='probleme_qualite_piece',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='recours_sav',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='satisfaction_delai_livraison',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='satisfaction_experience_rubio',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='satisfaction_qualite_pieces',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionb2b',
            name='type_probleme_qualite_piece',
            field=models.TextField(blank=True, null=True),
        ),
    ]
