# Generated by Django 5.2 on 2025-08-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_commercial_is_absent_alter_rendezvous_statut_rdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('RDV_AJOUTE', 'RDV Ajouté'), ('RDV_VALIDE', 'RDV Validé'), ('RDV_ANNULE', 'RDV Annulé'), ('CLIENT_AJOUTE', 'Client Ajouté'), ('ABSENCE_ON', 'Commercial absent'), ('ABSENCE_OFF', 'Commercial présent')], max_length=20),
        ),
        migrations.CreateModel(
            name='ClientVisitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('visites_valides', models.IntegerField(default=0, help_text='Nombre de visites validées cette année')),
                ('objectif', models.IntegerField(help_text='Objectif annuel de visites (A=10, B=5, C=1, défaut=1)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_visites', to='front.frontclient')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_visites', to='front.commercial')),
            ],
            options={
                'verbose_name': 'Statistique de visite client',
                'verbose_name_plural': 'Statistiques de visites clients',
                'indexes': [models.Index(fields=['client', 'annee'], name='front_clien_client__7ef476_idx'), models.Index(fields=['commercial', 'annee'], name='front_clien_commerc_e95f15_idx')],
                'unique_together': {('client', 'commercial', 'annee')},
            },
        ),
    ]
