# Generated by Django 5.2.1 on 2025-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_satisfactionb2b_commande_simple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='role',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('responsable', 'Responsable'), ('admin', 'Admin')], default='commercial', max_length=20),
        ),
    ]
