# Generated by Django 5.2.1 on 2025-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_commercial_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='rs_nom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
