# Generated by Django 5.2.1 on 2025-06-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_rendezvous_rs_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=150)),
                ('siret', models.CharField(max_length=14)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commercial_id', models.BigIntegerField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'front_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('RDV_AJOUTE', 'RDV Ajouté'), ('RDV_VALIDE', 'RDV Validé'), ('RDV_ANNULE', 'RDV Annulé'), ('CLIENT_AJOUTE', 'Client Ajouté')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.commercial')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
