# Generated by Django 5.2.1 on 2025-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_force_drop_front_client_backup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importclientcorrected',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='frontclient',
            name='classement_client',
            field=models.CharField(blank=True, help_text="Type de client (A, B, C) pour déterminer l'objectif annuel de visites", max_length=50, null=True),
        ),
    ]
