# Generated by Django 5.2.1 on 2025-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_alter_importclientcorrected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairerdv',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
