# Generated by Django 5.2.1 on 2026-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_commentairerdv_is_pinned'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(fields=('commercial', 'client', 'date_rdv', 'heure_rdv'), name='uniq_rdv_commercial_client_datetime'),
        ),
    ]
