# Generated by Django 5.2.1 on 2026-02-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_rendezvous_uniq_rdv_commercial_client_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_actor_logs', to='front.commercial'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
