# Default HTTPS : rejette tout hostname non prévu (évite d'exposer le cert)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;
    ssl_certificate /etc/letsencrypt/live/rubio-careco.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rubio-careco.cloud/privkey.pem;
    ssl_reject_handshake on;
}



# =========================
# Catch-all HTTP (ferme tout ce qui n'est pas ton domaine)
# =========================
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 444;
}

# HTTP -> HTTPS (ACME + redirection)
server {
    listen 80;
    listen [::]:80;
    server_name rubio-careco.cloud;

    # ACME challenge (Let's Encrypt)
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        access_log off;
    }

    location / {
        return 301 https://rubio-careco.cloud$request_uri;
    }
}

# HTTP www -> HTTPS apex
server {
    listen 80;
    listen [::]:80;
    server_name www.rubio-careco.cloud;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        access_log off;
    }

    location / {
        return 301 https://rubio-careco.cloud$request_uri;
    }
}

# HTTPS www -> HTTPS apex
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.rubio-careco.cloud;

    ssl_certificate     /etc/letsencrypt/live/rubio-careco.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rubio-careco.cloud/privkey.pem;

    return 301 https://rubio-careco.cloud$request_uri;
}

# =========================
# HTTPS principal (apex)
# =========================
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name rubio-careco.cloud;

    client_max_body_size 25m;

    ssl_certificate     /etc/letsencrypt/live/rubio-careco.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rubio-careco.cloud/privkey.pem;

    location = /favicon.ico {
    alias /app/staticfiles/front/img/logo-rubio1.png;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
}

    # HSTS (prod)
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Headers de base (safe)
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Static Django
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }

    # Proxy vers Django
    location / {
        proxy_pass         http://web:8000;
        proxy_http_version 1.1;

        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  https;
        proxy_set_header   X-Forwarded-Host   $host;
        proxy_set_header   X-Forwarded-Port   443;

        proxy_redirect off;
    }

    # Santé
    location = /healthz { add_header Content-Type text/plain; return 200 "ok\n"; }
}
